### ISSUE TITLE
Final formatting/polish checklist

### ISSUE THREAD

**Issue by nlicalzi** [dendro-naap/dendro-cli#114]
- [x] **General**
  - [x] Add and format `readme`
  - [x] Add inline documentation (to pieces that require it)
- [ ] **Server**
  - [x] Add Favicon to server (fixed by #109)
  - [x] Change website title (display on browser tab) (fixed by #109)
  - [ ] Add performance snapshot aggregate metrics for last day for nginx and apache (if those tables exist)
- [x] **CLI**
  - [x] Add `dendro help` and `dendro help [subcommand]` for all subcommands (fixed by #109)
  - [x] Add ASCII to relevant commands (fixed by #109)
  - [x] Finalize log messages and coloring
