### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by AndiLavera** [dendro-naap/dendro-cli#22]
# CLI Commands

- [ ] `configure` command (set up collectors) #21
- [ ] `review` command (pretty print current config setup before deploy)
- [x] `deploy` command (deploy pipeline using config settings)
- [x] `list` command (display current pipelines and elements)
- [ ] `teardown` command

# AWS

- [ ] S3
  - [x] create
  - [x] destroy
  - [ ] empty bucket
- [ ] Timestream
  - [x] create database
  - [ ] destroy database
  - [x] create table
  - [ ] destroy table
- [ ] Firehose
  - [x] create stream
  - [ ] destroy sream
- [ ] Lambda
  - [x] create lambda
  - [ ] destory lambda
  
 # Extras
